// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy2Mu5Ks8oicepgymRqFDZkALPqNXeeoE',
    appId: '1:78866155338:web:36cf2e5be092893acb63b3',
    messagingSenderId: '78866155338',
    projectId: 'flutterappmauricio',
    authDomain: 'flutterappmauricio.firebaseapp.com',
    storageBucket: 'flutterappmauricio.appspot.com',
    measurementId: 'G-J44F814G5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBYXqaadoaSL40PXEiNJ6xuEs0yFD36tc',
    appId: '1:78866155338:android:b8cc62ece436846ecb63b3',
    messagingSenderId: '78866155338',
    projectId: 'flutterappmauricio',
    storageBucket: 'flutterappmauricio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt7u2eGOCj4rh-WsHPAbSebkgVx1CN_oA',
    appId: '1:78866155338:ios:6870f4888b4dc01bcb63b3',
    messagingSenderId: '78866155338',
    projectId: 'flutterappmauricio',
    storageBucket: 'flutterappmauricio.appspot.com',
    iosClientId: '78866155338-3uki8gn62roeeede0382qithu4771bef.apps.googleusercontent.com',
    iosBundleId: 'com.example.snippets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt7u2eGOCj4rh-WsHPAbSebkgVx1CN_oA',
    appId: '1:78866155338:ios:6870f4888b4dc01bcb63b3',
    messagingSenderId: '78866155338',
    projectId: 'flutterappmauricio',
    storageBucket: 'flutterappmauricio.appspot.com',
    iosClientId: '78866155338-3uki8gn62roeeede0382qithu4771bef.apps.googleusercontent.com',
    iosBundleId: 'com.example.snippets',
  );
}
